@host = https://localhost:7163

### Register a new user
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "tudor@test.com",
  "password": "Test123!",
  "displayName": "Tudor"
}

### Login with the same user
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "tudor@test.com",
  "password": "Test123!"
}